### ISSUE TITLE
add suport off sqlite db with knex

### ISSUE THREAD

**Issue by alphaleadership** [antoinemcx/projet-amboise#2]
plusieurs base de donnée seront possible comme sa

**Comment by antoinemcx** [comment]
Pourquoi voudrais-je utiliser plusieurs bases de données ? Plutôt inutile pour le coup.

**Comment by alphaleadership** [comment]
quand je disait plusieur base de donnée c'est sql standart sqlite mariadb
et autre

**Comment by antoinemcx** [comment]
C'est bien ce que je dis, inutile.
Je sais pas pourquoi tu parles de ça, rien besoin d'ajouter en plus de mariadb.

Enfin bref, je ferme cette issue, si tu comprends pas envoie-moi un MP sur Discord :)
